export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_REPOS_ERROR = 'SEARCH_REPOS_ERROR';
export const SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR';
export const CLEAR_SEARCH_REPOS = 'CLEAR_SEARCH_REPOS';
export const CLEAR_SEARCH_USERS = 'CLEAR_SEARCH_USERS';